version: "3"


services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: updatime_robot_django
    container_name: updatime_robot_django
    env_file: ".env"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./:/app/


  postgres:
    image: postgres:13.3
    env_file: ".env"
    ports:
      - "7000:7000"
    volumes:
      - pg_data:/var/lib/postgresql/data


  redis:
    image: redis
    container_name: updatime_robot_redis


volumes:
  pg_data: {}
